language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
branches:
  only:
    - master
install:
  - pip install coveralls
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - nosetests -v  --with-coverage --cover-package=ptbtest/
after_success:
  - coveralls
  - codecov
